services:
  one-small-step:
    container_name: one-small-step

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    volumes:
      - ./config/config.yaml:/app/config/config.yaml:ro

    environment:
      CONFIG_PATH: /app/config/config.yaml
      FRONTEND_PATH: /app/frontend

    restart: unless-stopped
